import Head from 'next/head';
import { Inter } from 'next/font/google';
import Login from '@/components/login/Login';
import ResponsiveAppBar from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  
  return (
    <>
    <ResponsiveAppBar/>
      <Head>
        <title>Easy Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Login/>
    </>
  );
};